### ISSUE TITLE
Node Query Client Error 

### ISSUE THREAD

**Issue by carlobailey** [UDST/osmnet#14]
#### Description of the bug
I am trying to retrieve NYC's network using OSMnet and am running into a HTTP 400 error when  replicating code from [this](https://github.com/gboeing/urban-data-science/blob/master/20-Accessibility-Walkability/pandana-accessibility-demo-full.ipynb)

Full traceback:
```python
File "/usr/local/lib/python2.7/site-packages/pandana/loaders/osm.py", line 183, in node_query
    lat_min, lng_min, lat_max, lng_max, tags=tags))
  File "/usr/local/lib/python2.7/site-packages/pandana/loaders/osm.py", line 115, in make_osm_query
    req.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://www.overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%3B%28++node++%5B%22amenity%22%3D%22restaurant%22%5D++%2840.917577%2C40.477399%2C-73.700272%2C-74.25909%29%3B%29%3Bout%3B
```

#### OSM data (optional) 
Bounding box data if it helps:
```python
bbox = [40.917577, 40.477399, -73.700272, -74.259090] #lat-long bounding box for NYC
```

#### Environment 

- Operating system:
OS Sierra
- Python version:
2.7
- OSMnet version:
0.1.5
- OSMnet required packages versions (optional):

#### Paste the code that reproduces the issue here:

```python
import pandana
from pandana.loaders import osm


bbox = [40.917577, 40.477399, -73.700272, -74.259090] #lat-long bounding box for NYC

osm_tags = '"amenity"="restaurant"'
pois = osm.node_query(bbox[0], bbox[1], bbox[2], bbox[3], tags=osm_tags)
```

#### Paste the error message (if applicable):
```python
File "/usr/local/lib/python2.7/site-packages/pandana/loaders/osm.py", line 183, in node_query
    lat_min, lng_min, lat_max, lng_max, tags=tags))
  File "/usr/local/lib/python2.7/site-packages/pandana/loaders/osm.py", line 115, in make_osm_query
    req.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://www.overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%3B%28++node++%5B%22amenity%22%3D%22restaurant%22%5D++%2840.917577%2C40.477399%2C-73.700272%2C-74.25909%29%3B%29%3Bout%3B
```

**Comment by sablanchard** [comment]
Hi @carlobailey, the function you are referring to here is part of Pandana not part of OSMnet it is located here: https://github.com/UDST/pandana/blob/c578b03930f447e183ba20b274916e12a9cc44a1/pandana/loaders/osm.py#L160-L189 but it looks like you have the coordinates for the bbox in the wrong order in the `osm.node_query()` function and it should follow this format: https://github.com/UDST/pandana/blob/c578b03930f447e183ba20b274916e12a9cc44a1/pandana/loaders/osm.py#L166

If you do this instead:
`pois = osm.node_query(bbox[2], bbox[3], bbox[0], bbox[1], tags=osm_tags)`

It works fine and I am able to get 115,792 results returned.

Will close the issue.
