### ISSUE TITLE
Network from bbox func should support either explicit lat/lons or bbox tuple - not both

### ISSUE THREAD

**Issue by kuanb** [UDST/osmnet#6]
Referring to the keyword arguments in this function (`network_from_bbox`): https://github.com/UDST/osmnet/blob/master/osmnet/load.py#L741

I can appreciate the desire to support inclusion of keyword arguments for the bounding box in more than one format, but in this case it seems (in my opinion) that the "downstream" costs are greater than any gains in flexibility. Specifically, one has to dig all the way to [this check statement](https://github.com/UDST/osmnet/blob/master/osmnet/load.py#L795) to realize that the reason why the lat/lon options are there is to be an alternative to the `bbox`.

This ultimately is the opinion of me as a user, but clarity in what arguments a function can take (in this case) supersedes the flexibility gains of allows us to input in either format.

I'd propose dropping support for `lat/lon` being submitted separately and enforce submission by the standard `bbox` 4-length tuple.

In other libraries that have employed this, such as [this function](https://github.com/UDST/urbanaccess/blob/3b0e9299c812f0376cefc3e9db3dd593c534d27d/urbanaccess/osm/load.py#L15), we can see how this function is negatively impacting the clarity of associated functions and creating bloated argument parameters.

My initial instinct as a user was to attempt to supply this (and be confused):
```
urbanaccess.osm.load.ua_network_from_bbox(
                                    bbox[0],
                                    bbox[1],
                                    bbox[2],
                                    bbox[3],
                                    bbox,
                                    network_type='walk',
                                    timeout=180,
                                    memory=None,
                                    max_query_area_size=2500000000L,
                                    remove_lcn=True)
```

A more ideal situation would be to just enforce the tuple format such that the supplied arguments would look akin to:
```
urbanaccess.osm.load.ua_network_from_bbox(
                                    bbox,
                                    network_type='walk',
                                    timeout=180,
                                    memory=None,
                                    max_query_area_size=2500000000L,
                                    remove_lcn=True)
```

**Comment by sablanchard** [comment]
Thank you for the suggestion Kuan! I agree that simplifying the bbox parameters would be ideal however, we would like to support two distinct ways in which users may be comfortable in specifying a bbox. The lat_min, lng_min, lat_max, lng_max parameters allow for explicit coordinate definitions to be applied that does not follow a coordinate pair convention (sometimes coordinate order and pairs in a tuple format can be confusing and specific parameters allow for a explicit definition) while the bbox parameter allows for the use of the bbox format that follows the coordinate pair convention used by http://boundingbox.klokantech.com/ (which does not follow more conventional coordinate pair formats).

To help clarify the bbox parameters I have expanded the docstring: https://github.com/UDST/osmnet/commit/61c9710bddd8e0fa71e42557a12f90b404b5b25c

I will close this issue for now and would be happy to revisit it in the future.
