### ISSUE TITLE
Tags-to-keep from Overpass API might need to be updated 

### ISSUE THREAD

**Issue by kuanb** [UDST/osmnet#7]
Just a heads up that the tags that are identified as needing to be kept on this line:
https://github.com/UDST/osmnet/blob/master/osmnet/config.py#L61

are different than what is currently on the master branch of OSMnx. See the line in that lib here:
https://github.com/gboeing/osmnx/blob/8f9308fa43758baefe11f42d0388d22e9f4e2589/osmnx/globals.py#L29

Tags such as "area" may be useful in curating out polygons from ways results (which could lead to errors downstream when using this for routing purposes).

**Comment by sablanchard** [comment]
Addressed in v0.1.5 via #11
