### ISSUE TITLE
Suggested feature: custom OSM filters

### ISSUE THREAD

**Issue by lmnoel** [UDST/osmnet#8]
#### Suggestion

User should be able to supply custom OSM filter when calling network_from_bbox

The two predefined filter choices for 'walk' and 'drive' are helpful, but somewhat limiting. Adding this would allow for much greater generalizability.

**Comment by sablanchard** [comment]
Thank you for the feature request @lmnoel! Yes this would be a good feature. We probably will not be able to get to a feature like this for some time however we welcome PRs to the package for things such as this and we can provide assistance and review along the way if anyone is interested in taking this on.

**Comment by sablanchard** [comment]
Thanks @lmnoel will review your PR #9 later this week.

**Comment by sablanchard** [comment]
Added in v0.1.5 via #11
